#!/bin/sh

# Projects
export DEV_FOLDER=$HOME/dev
export WS_FULL_METAL=$DEV_FOLDER/monobased/apps/full-metal-template
export WS_CX_CLOUD=$DEV_FOLDER/cx-cloud-ui
export WS_CHOICE_PLUS=$DEV_FOLDER/cx-cloud-ui/libs/shared/choice-plus
export WS_NOTES=$DEV_FOLDER/notes
export WS_FLOTES=$DEV_FOLDER/flotes
export WS_TASKS=$DEV_FOLDER/task-manager
export WS_SWITCHER=$DEV_FOLDER/nvim-quick-switcher
export WS_PLAYGROUND=$DEV_FOLDER/erxk-article-playground
export WS_ZSH=$HOME/.config/zsh/
export WS_AWESOME=$HOME/.config/awesome
export WS_SCRIPTS=$HOME/.config/lua-scripts
export WS_NVIM=$HOME/.config/nvim
export WS_ALACRITTY=$HOME/.config/alacritty
export WS_DOTFILES=$HOME/dotfiles
export WS_SNIPPETS_FILE=$HOME/.config/nvim/lua/luasnip-config.lua
export WS_SVELTE_PLAYGROUND=$DEV_FOLDER/starter-template
export WS_BLOG_FLOTES=$DEV_FOLDER/flotes-blog
export WS_TOMATILLO=$DEV_FOLDER/tomatillo

eval "$(fnm env)"


# Misc
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export NODE_OPTIONS=--max_old_space_size=16384
