require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.utility"
require "user.tokyo-night"
require "user.catppuccin"
require "user.colorizer"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.terminal"
require "user.alpha"
require "user.whichkey"
require "user.harpoon"
require "user.switcher"
require "user.luasnip"
require "user.dap-config"
require "user.dad-bod"
-- require "user.octo"
require "user.comment"
require "user.indent-line"
require "user.lsp.typescript-ls"
require "user.lsp.html-ls"
-- require "user.lsp.lua-ls"
require "user.lsp.null-ls"
require "user.mason"
require "user.lsp.angular-ls"
require "user.lsp.emmet-ls"
require "user.lsp.tailwindcss-ls"
require "user.lsp.astro-ls"
require "user.lsp.svelte-ls"
require "user.zen"
