#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


# My Variables
export DEV_FOLDER=Documents/dev
export WS_FULL_METAL=$HOME/$DEV_FOLDER/monobased/apps/full-metal-template
export WS_CX_CLOUD=$HOME/$DEV_FOLDER/cx-cloud-ui-worktree/main/apps/cx-portal
export WS_NOTES=$HOME/$DEV_FOLDER/notes
export WS_PLAYGROUND=$HOME/$DEV_FOLDER/erxk-article-playground
export WS_CONFIG=$HOME/dotfiles
export WS_ZSHRC=$WS_CONFIG/zsh/.config/zsh/.zshrc


# TODO: Removed
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

